### PR TITLE
Payloads cleanup

### PR DESCRIPTION
**Pull request by madroneropaulo**
Decouple messages payloads by name. Removed unnecessary cases (they can be viewed at payloadmap.js and used when needed). Added support for two parameters logTraffic and logData (they may be useful for better understanding of the communication).
Usage:
$ node app.js logTraffic => Logs the message name.
$ node app.js logData => Logs the payload data.
$ node app.js logData logTraffic => logs both.

[recommended] Use with chrome debugger:
$ npm install -g node-inspector

$node-debug app.js logData logTraffic

### CODE REVIEW

**Comment by spotware** [comment]
Magic numbers were replaced by constants.
Please adjust your code.

**Comment by madroneropaulo** [comment]
Ok done.

**Comment by spotware** [comment]
Merge conflict

**Comment by madroneropaulo** [comment]
No longer needed

**Pull request closed without merging**
